dist: trusty

language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=4.9 WP_MULTISITE=0
  - WP_VERSION=4.8 WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=0

matrix:
  fast_finish: true
  include:
  - php: 5.5
    env: WP_VERSION=4.7 WP_MULTISITE=1

before_install:
  - composer self-update

before_script:
  - mysql -e "create database IF NOT EXISTS wpemerge_tests;" -uroot
  - bash tests/bin/install.sh wpemerge_tests root '' localhost $WP_VERSION

script:
  # Check all PHP files for syntax errors.
  # The usage of bash + || exit 1 is to ensure xargs does not exit on first error.
  - find src/ \( -name '*.php' \) | xargs -n1 bash -c 'php -lf $0 || exit 1'
  - phpunit --coverage-clover=./tmp/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./tmp/clover.xml
