name: PHP Composer

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '7.1', '7.0' ]
        wp-versions: ['5.9', '5.8', '5.7']
        include:
          - php-versions: '8.1'
            wp-versions: '5.9'
          - php-versions: '8.0'
            wp-versions: '5.9'
          - php-versions: '5.6'
            wp-versions: '4.7'
          - php-versions: '5.5'
            wp-versions: '4.7'
        # php-versions: ['5.5']
        # wp-versions: ['4.7']
        # phpunit-versions: ['7.5.20']
        # include:
        # - operating-system: 'ubuntu-latest'
        #   php-versions: '7.2'
        #   phpunit-versions: '8.5.21'

    steps:
      - uses: actions/checkout@v3

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '5.7'
          my-cnf: |
            collation_server=utf8_unicode_ci
            character_set_server=utf8
          # root-password: ${{ env.DB_PASS }}

      - name: Set up database
        run: mysql -uroot -h127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS wpemerge_tests;'

      - name: Install WordPress
        run: bash tests/bin/install.sh wpemerge_tests root '' 127.0.0.1 ${{ matrix.wp-versions }}

      - name: Does GitHub ruin my shhhstuff?
        run: cat tmp/wordpress-tests-lib/wp-tests-config.php

      # - name: Clone WordPress
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 'git://develop.git.wordpress.org/'
      #     ref: ${{ matrix.wp-versions }}
      #     path: ${{ env.WP_DIR }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          # tools: phpunit

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      # - name: Cache Composer packages
      #   id: composer-cache
      #   uses: actions/cache@v3
      #   with:
      #     path: vendor
      #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Install PHPUnit
        run: composer run install-test-env

      - name: Validate PHP syntax
        run: find src/ \( -name '*.php' \) | xargs -n1 bash -c 'php -lf $0 || exit 1'

      - name: Run tests
        run: composer run test

      - name: Upload coverage to Scrutinizer-CI.
        run: wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./tmp/clover.xml
